### ISSUE TITLE
add student option for system managers

### ISSUE THREAD

**Issue by AAP67** [SSMS-Pilani/Mess-Management-System#10]

**Comment by MVikhona** [comment]
Started working on it.

**Comment by AAP67** [comment]
update?

**Comment by MVikhona** [comment]
Completed. Please review it.

**Comment by devenbansod** [comment]
Hi @MVikhona, it is generally great to work on a different branch of your own forked copy of the repository, and then send a Pull Request to Main repository's Master branch. 

This allows the administrator to review and then merge your commits to master branch. Once, you have already pushed the commits to master, it does not make much sense to "review" it as such.

**Comment by devenbansod** [comment]
But good to see some active development going on around this repository after so long. Keep it up! :)

**Comment by MVikhona** [comment]
Sorry. Actually I don't know much about using GIT , but I m learning . From the next time I will work on a different Branch . Still Please use it , and see if there are any bugs.
